.TH "blobdrop" 1 "07 July 2022" "" "blobdrop Documentation"

.SH NAME
blobdrop \- Quickly drag and drop files from the terminal to applications

.SH SYNOPSIS
.B blobdrop
[\-hvfiklnpt]
[\-x \fINUM\fP]
.I FILES

.SH DESCRIPTION

.P
This program allows you to drag files directly from the terminal to other applications.
It can be used both as a source (files can be dragged from the terminal) and as a sink (dropped file names will be printed in the terminal).

Filenames can either be given as command line arguments or by piping them into stdin, one filename per line.

Several frontends are available to drag files from. By default, blobdrop will automatically determine the best frontend, meaning that for a single given file it will immediately start the drag operation without having to hold down the mouse while showing a window when multiple files are provided.
The frontend can be manually selected with the \-\-frontend option.

.TP
.B \-h, \-\-help
Show help.
.TP
.B \-v, \-\-version
Show version information.
.TP
.B \-b, \-\-frameless
Show a frameless window.
.TP
.B \-f, \-\-frontend
Selects the frontend. Must be one of {auto (default), gui, immediate, notify, link}. Selecting auto will choose gui if there are more than one elements to be dragged and immediate otherwise. Choosing gui starts a window, immediate will start the drag immediately not requiring the user to hold the mouse button, notify will allow to drag from a notification using the x-kde-urls extension and link will print an OSC8 link in the terminal.
.TP
.B \-k, \-\-keep
When using sink mode, keep dropped files around by default.
.TP
.B \-p, \-\-persistent
Do not auto-hide the main window while dragging.
.TP
.B \-t, \-\-ontop
Keep the window on top of other windows.
.TP
.B \-x, \-\-auto-quit \fINUM
Changes the conditions when blobdrop will automatically quit. Must be one of {never, first, all}. For never it will never automatically quit, for first it will quit after the first drag and for all (default value) it will quit once every path has been dragged at least once.

.SH EXIT STATUS
Returns zero on success.
