.TH "blobdrop" 1 "07 July 2022" "" "blobdrop Documentation"

.SH NAME
blobdrop \- Quickly drag and drop files from the terminal to applications

.SH SYNOPSIS
.B blobdrop
[\-h]
[\-v]
[\-f]
[\-k]
[\-p]
[\-t]
[\-x \fINUM\fP]
.I FILES

.SH DESCRIPTION

.P
This program allows you to drag files directly from the terminal to other applications.
It can be used both as a source (files can be dragged from the terminal) and as a sink (dropped file names will be printed in the terminal).

Filenames can either be given as command line arguments or by piping them into stdin, one filename per line.

.TP
.B \-h, \-\-help
Show help.
.TP
.B \-v, \-\-version
Show version information.
.TP
.B \-f, \-\-frameless
Show a frameless window.
.TP
.B \-k, \-\-keep
When using sink mode, keep dropped files around by default.
.TP
.B \-n, \-\-notification
Send a notification for dragging.
.TP
.B \-p, \-\-persistent
Do not auto-hide the main window while dragging.
.TP
.B \-t, \-\-ontop
Keep the window on top of other windows.
.TP
.B \-x, \-\-auto-quit \fINUM
Changes the conditions when blobdrop will automatically quit. For 0 it will never automatically quit, for 1 it will quit after the first drag and for 2 (default value) it will quit once every path has been dragged at least once.

.SH EXIT STATUS
Returns zero on success.
